package com.example.local_notebooklm.controller;

import com.example.local_notebooklm.dto.ChatResponse;
import com.example.local_notebooklm.service.ChatbotService;
import org.springframework.web.bind.annotation.*;

@RestController
@CrossOrigin(origins = "*")
@RequestMapping("/api/chat")
public class ChatController {

    private final ChatbotService chatbotService;

    public ChatController(ChatbotService chatbotService) {
        this.chatbotService = chatbotService;
    }

    /**
     * Run the full CRAG pipeline for a question scoped to one document.
     *
     * sessionId: UUID generated by the browser on first load. Each browser tab
     * gets its own isolated conversation memory window. If omitted, all requests
     * share a "default-session" — fine for single-user dev, problematic in prod.
     *
     * GET /api/chat/ask?question=...&filename=...&sessionId=...&minScore=0.70&maxResults=10
     */
    @GetMapping("/ask")
    public ChatResponse askAI(
            @RequestParam String question,
            @RequestParam String filename,
            @RequestParam(required = false, defaultValue = "default-session") String sessionId,
            @RequestParam(defaultValue = "0.70") double minScore,
            @RequestParam(defaultValue = "10")   int maxResults) {
        return chatbotService.askAdvancedQuestion(question, minScore, maxResults, filename, sessionId);
    }

    /**
     * Clear the conversation memory for a specific session.
     * POST /api/chat/clear?sessionId=...
     */
    @PostMapping("/clear")
    public String clearHistory(
            @RequestParam(required = false, defaultValue = "default-session") String sessionId) {
        chatbotService.clearHistory(sessionId);
        return "✅ Conversation memory cleared for session: " + sessionId;
    }
}
